name: commit451
description: Website for Commit 451

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/firacode-bold.ttf
